### PR TITLE
Fix compatibility with macOS 14

### PR DESCRIPTION
**Pull request by ExtremeXT**

### CODE REVIEW

**Comment by xyzuan** [comment]
niceee

**Comment by ExtremeXT** [comment]
@vit9696

**Comment by vit9696** [comment]
Tyvm!

**Comment by MrDuartePT** [comment]
Well using Mac OS Sonoma (14.5) or Ventura on MacBook Pro 14,1 refuses to boot with startup error. I can try get OpenCore Boot logs.

**Pull request merged**
