### PR TITLE
Add constants for macOS 15/Sequoia support

### PR DESCRIPTION
**Pull request by AlfCraft07**

### CODE REVIEW

**Review by aslua — APPROVED** [review]

**Comment by vit9696** [comment]
Was it tested? Could you provide debug logs with -liludbgall liludump=120?

**Comment by AlfCraft07** [comment]
> Was it tested? Could you provide debug logs with -liludbgall liludump=120?

Unfortunately I have no computers using NVMe, but I saw a couple of posts on Reddit from people being able to load the original version using -lilubetaall

**Comment by vit9696** [comment]
Being able to load does not mean the kext works.

**Review by EAZYBLACK — APPROVED** [review]

**Comment by EAZYBLACK** [comment]
> Was it tested? Could you provide debug logs with -liludbgall liludump=120?

Tested it, Sequoia Beta 7, works fine 
I have one nvme intenso and one nvme crucial p3, both work fine
[Lilu_1.6.8_24.0.txt](https://github.com/user-attachments/files/16797262/Lilu_1.6.8_24.0.txt)

**Comment by vit9696** [comment]
To be honest, it does not seem to be working. In the logs we have the following lines (copied from various places in the log):

```
NVMeFix    disasm: @ (DBG) Failed to find ANS2MSIWorkaround
NVMeFix   feature: @ (DBG) ProcessSyncNVMeRequest failed
NVMeFix     nvmef: @ (DBG) Failed to configure APST with 0xe00002c7
NVMeFix        pm: @ registerPowerDriver failed with 0xe00002c2
NVMeFix        pm: @ Failed to initialise power management
```

They signalise that NVMeFix is not working as intended. While your SSDs work fine, I believe NVMeFix does nit change anything in their behaviour. I.e. they work as good and as bad as without NVMeFix.

**Comment by EAZYBLACK** [comment]
> To be honest, it does not seem to be working. In the logs we have the following lines (copied from various places in the log):
> 
> ```
> NVMeFix    disasm: @ (DBG) Failed to find ANS2MSIWorkaround
> NVMeFix   feature: @ (DBG) ProcessSyncNVMeRequest failed
> NVMeFix     nvmef: @ (DBG) Failed to configure APST with 0xe00002c7
> NVMeFix        pm: @ registerPowerDriver failed with 0xe00002c2
> NVMeFix        pm: @ Failed to initialise power management
> ```
> 
> They signalise that NVMeFix is not working as intended. While your SSDs work fine, I believe NVMeFix does nit change anything in their behaviour. I.e. they work as good and as bad as without NVMeFix.

I tested on monterey and same stuff happen as u said above
So i dont think this is because sequoia
[Lilu_1.6.8_21.6.txt](https://github.com/user-attachments/files/16923659/Lilu_1.6.8_21.6.txt)

**Comment by vit9696** [comment]
That only means that macOS 14 is broken as well.

**Comment by AlfCraft07** [comment]
That log is from Monterey, not Sonoma

**Comment by sandr8** [comment]
Any update on this?

**Comment by MatteoBax** [comment]
> Was it tested? Could you provide debug logs with -liludbgall liludump=120?

My NVMe SSD isn't supported by this kext so I don't know if the logs are actually correct.
[Lilu_1.6.9_24.0.txt](https://github.com/user-attachments/files/17606400/Lilu_1.6.9_24.0.txt)

**Comment by EAZYBLACK** [comment]
Why not merge it , since same log shows in monterey and sequoia, ANS2MSIWorkaround is probably broken in big sur+

**Comment by stigdk** [comment]
Tested on MBA Early 2017 15.1 (24B83) w. Crucial P3 1TB SSD. 1.1.2 Kext loads and expected apst and NVMePMProxy values are present. Replaced the 1.1.1 version installed by OC.

**Pull request merged**
